### ISSUE TITLE
check-roomalert reports wrong, when temperature below 10 degrees C

### ISSUE THREAD

**Issue by hoerup** [ranl/monitor-utils#25]
The current calculation from centidegrees(?) to degrees contains an error.

When temperature is below 10 degrees the raw value is only 3 digits long, so by allways taking the first 2 digits, the calculated value ends up as eg 99 degreess instead of 9.9 degrees

I've fixed locally by using this line instead
$internal = $internal / 100.0;

**Comment by ranl** [comment]
thanks @hoerup, do u wanna send a pull request ?

**Comment by hoerup** [comment]
Sure, see https://github.com/ranl/monitor-utils/pull/26

**Comment by ranl** [comment]
thanks @hoerup !
